language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - "yarn add global gatsby"
  - "yarn install"
script:
  - "yarn build"
after_success:
  - "yarn deploy"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: develop
